import { Menu } from "@/types/menu";
import {
  Archive,
  Award,
  BookOpen,
  Briefcase,
  CalendarDays,
  FileText,
  Globe,
  GraduationCap,
  HandHeart,
  Handshake,
  Heart,
  HeartHandshake,
  Leaf,
  Library,
  Lightbulb,
  MapPin,
  Medal,
  MessageCircleHeart,
  Microscope,
  Newspaper,
  Quote,
  Sprout,
  Target,
  Trophy,
  Users,
} from "lucide-react";

// One icon per meaning — no two items in the same dropdown share an icon, and
// each one should read as its label (QA #17: Research and Scholarships were
// both an Award, and Counselling borrowed Donate's heart).

const menuData: Menu[] = [
  {
    id: 1,
    title: "About Us",
    path: "/about",
    newTab: false,
    submenu: [
      {
        id: 11,
        title: "Our Vision & Mission",
        path: "/about/mission-vision",
        newTab: false,
        icon: Target,
      },
      {
        id: 12,
        title: "Who We Are",
        path: "/about/who-we-are",
        newTab: false,
        icon: Users,
      },
      {
        id: 13,
        title: "Where We Work",
        path: "/about/where-we-work",
        newTab: false,
        icon: MapPin,
      },
      {
        id: 14,
        title: "Annual Reports & Financials",
        path: "/about/reports",
        newTab: false,
        icon: FileText,
      },
      {
        id: 15,
        title: "News & Press",
        path: "/news",
        newTab: false,
        icon: Newspaper,
      },
      {
        id: 16,
        title: "Archive",
        path: "/about/archive",
        newTab: false,
        icon: Archive,
      },
    ],
  },
  {
    id: 2,
    title: "What We Do",
    path: "/what-we-do",
    newTab: false,
    submenu: [
      {
        id: 20,
        title: "Our Projects",
        path: "/projects",
        newTab: false,
        icon: Lightbulb,
      },
      {
        id: 21,
        title: "Student Counselling",
        path: "/what-we-do/student-counselling",
        newTab: false,
        icon: MessageCircleHeart,
      },
      {
        id: 22,
        title: "Parent Advocacy",
        path: "/what-we-do/parent-advocacy",
        newTab: false,
        icon: HeartHandshake,
      },
      {
        id: 23,
        title: "Minor Community Wellbeing",
        path: "/what-we-do/community-wellbeing",
        newTab: false,
        icon: HandHeart,
      },
      {
        id: 24,
        title: "Climate Action and Environmental Stewardship",
        path: "/what-we-do/climate-action",
        newTab: false,
        icon: Leaf,
      },
      {
        id: 25,
        title: "Research & Publications",
        path: "/what-we-do/research-publications",
        newTab: false,
        icon: Microscope,
      },
      {
        id: 26,
        title: "Scholarships & Grants",
        path: "/what-we-do/scholarships-grants",
        newTab: false,
        icon: GraduationCap,
      },
    ],
  },
  {
    id: 3,
    title: "Blog",
    path: "/blog",
    newTab: false,
    submenu: [
      {
        id: 31,
        title: "Magazine",
        path: "/blog/magazine",
        newTab: false,
        icon: BookOpen,
      },
      {
        id: 32,
        title: "Education and Career Blog",
        path: "/blog/education-career",
        newTab: false,
        icon: Library,
        submenu: [
          {
            id: 321,
            title: "Career",
            path: "/blog/education-career/career",
            newTab: false,
            icon: Briefcase,
          },
          {
            id: 322,
            title: "Higher Study",
            path: "/blog/education-career/higher-study",
            newTab: false,
            icon: GraduationCap,
          },
          {
            id: 323,
            title: "Self-Development",
            path: "/blog/education-career/self-development",
            newTab: false,
            icon: Sprout,
          },
          {
            id: 324,
            title: "Parenting",
            path: "/blog/education-career/parenting",
            newTab: false,
            icon: Users,
          },
          {
            id: 325,
            title: "Social Issues",
            path: "/blog/education-career/social-issues",
            newTab: false,
            icon: Globe,
          },
          {
            id: 326,
            title: "Scholarship Opportunities",
            path: "/blog/education-career/scholarship-opportunities",
            newTab: false,
            icon: Award,
          },
          {
            id: 327,
            title: "Competitions",
            path: "/blog/education-career/competitions",
            newTab: false,
            icon: Trophy,
          },
          {
            id: 328,
            title: "Olympiads",
            path: "/blog/education-career/olympiads",
            newTab: false,
            icon: Medal,
          },
        ],
      },
      {
        id: 33,
        title: "Real Life Stories",
        path: "/blog/real-life-stories",
        newTab: false,
        icon: Quote,
      },
      {
        id: 34,
        title: "Events",
        path: "/blog/events",
        newTab: false,
        icon: CalendarDays,
      },
    ],
  },
  {
    id: 4,
    title: "Get Involved",
    newTab: false,
    submenu: [
      {
        id: 41,
        title: "Donate",
        path: "/get-involved/donate",
        newTab: false,
        icon: Heart,
      },
      {
        id: 42,
        title: "Partner With Us",
        path: "/get-involved/partner",
        newTab: false,
        icon: Handshake,
      },
      // "Careers" lived here and led to a 404 — there is no careers page or
      // content yet. Add it back alongside a real /get-involved/careers route.
    ],
  },
  {
    id: 5,
    title: "Find Us",
    path: "/contact",
    newTab: false,
  },
];
export default menuData;
