import { Menu } from "@/types/menu";
import { Target, Users, MapPin, FileText, Eye, BookOpen, Heart, Building, Globe, Award, Briefcase, Handshake, CalendarDays, Sparkles } from "lucide-react";

const menuData: Menu[] = [
  {
    id: 1,
    title: "About Us",
    path: "/about",
    newTab: false,
    submenu: [
      {
        id: 11,
        title: "Our Vision & Mission",
        path: "/about/mission-vision",
        newTab: false,
        icon: Target,
      },
      {
        id: 12,
        title: "Who We Are",
        path: "/about/who-we-are",
        newTab: false,
        icon: Users,
      },
      {
        id: 13,
        title: "Where We Work",
        path: "/about/where-we-work",
        newTab: false,
        icon: MapPin,
      },
      {
        id: 14,
        title: "Annual Reports & Financials",
        path: "/about/reports",
        newTab: false,
        icon: FileText,
      },
      {
        id: 15,
        title: "News & Press",
        path: "/news",
        newTab: false,
        icon: Eye,
      },
      {
        id: 16,
        title: "Archive",
        path: "/about/archive",
        newTab: false,
        icon: BookOpen,
      },
    ],
  },
  {
    id: 2,
    title: "What We Do",
    path: "/what-we-do",
    newTab: false,
    submenu: [
      {
        id: 20,
        title: "Our Projects",
        path: "/projects",
        newTab: false,
        icon: Sparkles,
      },
      {
        id: 21,
        title: "Student Counselling",
        path: "/what-we-do/student-counselling",
        newTab: false,
        icon: Heart,
      },
      {
        id: 22,
        title: "Parent Advocacy",
        path: "/what-we-do/parent-advocacy",
        newTab: false,
        icon: Users,
      },
      {
        id: 23,
        title: "Minor Community Wellbeing",
        path: "/what-we-do/community-wellbeing",
        newTab: false,
        icon: Building,
      },
      {
        id: 24,
        title: "Climate Action and Environmental Stewardship",
        path: "/what-we-do/climate-action",
        newTab: false,
        icon: Globe,
      },
      {
        id: 25,
        title: "Research & Publications",
        path: "/what-we-do/research-publications",
        newTab: false,
        icon: Award,
      },
      {
        id: 26,
        title: "Scholarships & Grants",
        path: "/what-we-do/scholarships-grants",
        newTab: false,
        icon: Award,
      },
    ],
  },
  {
    id: 3,
    title: "Blog",
    path: "/blog",
    newTab: false,
    submenu: [
      {
        id: 31,
        title: "Magazine",
        path: "/blog/magazine",
        newTab: false,
        icon: BookOpen,
      },
      {
        id: 32,
        title: "Education and Career Blog",
        path: "/blog/education-career",
        newTab: false,
        icon: BookOpen,
        submenu: [
          {
            id: 321,
            title: "Career",
            path: "/blog/education-career/career",
            newTab: false,
            icon: Briefcase,
          },
          {
            id: 322,
            title: "Higher Study",
            path: "/blog/education-career/higher-study",
            newTab: false,
            icon: BookOpen,
          },
          {
            id: 323,
            title: "Self-Development",
            path: "/blog/education-career/self-development",
            newTab: false,
            icon: Target,
          },
          {
            id: 324,
            title: "Parenting",
            path: "/blog/education-career/parenting",
            newTab: false,
            icon: Users,
          },
          {
            id: 325,
            title: "Social Issues",
            path: "/blog/education-career/social-issues",
            newTab: false,
            icon: Globe,
          },
          {
            id: 326,
            title: "Scholarship Opportunities",
            path: "/blog/education-career/scholarship-opportunities",
            newTab: false,
            icon: Award,
          },
          {
            id: 327,
            title: "Competitions",
            path: "/blog/education-career/competitions",
            newTab: false,
            icon: Award,
          },
          {
            id: 328,
            title: "Olympiads",
            path: "/blog/education-career/olympiads",
            newTab: false,
            icon: Award,
          },
        ],
      },
      {
        id: 33,
        title: "Real Life Stories",
        path: "/blog/real-life-stories",
        newTab: false,
        icon: FileText,
      },
      {
        id: 34,
        title: "Events",
        path: "/blog/events",
        newTab: false,
        icon: CalendarDays,
      },
    ],
  },
  {
    id: 4,
    title: "Get Involved",
    newTab: false,
    submenu: [
      {
        id: 41,
        title: "Donate",
        path: "/get-involved/donate",
        newTab: false,
        icon: Heart,
      },
      {
        id: 42,
        title: "Partner With Us",
        path: "/get-involved/partner",
        newTab: false,
        icon: Handshake,
      },
      {
        id: 43,
        title: "Careers",
        path: "/get-involved/careers",
        newTab: false,
        icon: Briefcase,
      },
    ],
  },
  {
    id: 5,
    title: "Find Us",
    path: "/contact",
    newTab: false,
  },
];
export default menuData;
